#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings

from scrariva.spiders.ariva import Ariva

import sys

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: ./ariva ISIN")
        sys.exit(1)

    isin = sys.argv[1]

    process = CrawlerProcess(get_project_settings())
    process.crawl(Ariva, isin=isin, outdir='.')
    process.start()
